---
language: java
cache: pip

services:
  - docker

script:
  - set -e
  - mvn clean test

after_success:
  - sudo pip install awscli
  - ./runtimes/build-all-linux
  - ./runtimes/build-all-macos
  - ./runtimes/deploy-to-s3 bazile.jenkins.python
