#!/usr/bin/env python3

import argparse
import datetime
import glob
import json
import os
import re
import subprocess


START_TIME        = datetime.datetime.now()

STAGING_ROOT      = os.path.abspath(os.path.join(os.path.dirname(__file__), '.staging'))
PATTERN_FILENAME  = re.compile(r'^python-(?P<version>\d+\.\d+\.\d+)-(?P<platform>[a-z]+)\.tar\.gz(?:\.shasum)?$''', re.I)

ID_TEMPLATE       = '{version}-{platform}'
NAME_TEMPLATE     = '{version}'
MANIFEST_FILENAME = 'org.bazile.jenkins.python.PythonInstaller.json'
MANIFEST_TEMPLATE = "downloadService.post('org.bazile.jenkins.python.PythonInstaller', {runtimes})\n"
URL_TEMPLATE      = 'https://s3.amazonaws.com/{bucket}/{filename}'


def main():
    ensure_aws_cli()

    enter_staging_root()

    parser = argparse.ArgumentParser()
    parser.add_argument('bucket')
    opts = parser.parse_args()

    bucket_name = os.path.basename(opts.bucket)

    print_message('preparing deployment to s3://%s', bucket_name, prefix='<<<', pad='before')

    write_manifest(bucket_name)

    print_message('deploying', prefix='>>>', pad='after')
    deploy(bucket_name)

    print_message('all runtimes deployed (elapsed=%s)', time_elapsed(), prefix='>>>', pad='both')


def deploy(bucket_name: str):
    execute_subprocess(STAGING_ROOT, [
        'aws',
        's3',
        'sync',
        '--delete',
        '.',
        's3://{}'.format(bucket_name),
    ])


def ensure_aws_cli():
    try:
        execute_subprocess(STAGING_ROOT, ['aws', '--version'])
    except FileNotFoundError:
        fail('cannot continue; aws CLI was not found in your PATH')


def enter_staging_root():
    os.chdir(STAGING_ROOT)


def execute_subprocess(cwd: str, command_args: list, border: str = 'both'):
    if border in ('before', 'both'):
        print('=' * 80)

    print('\033[31m+ {}\033[0m'.format(' '.join(command_args)))
    exit_code = subprocess.call(args=command_args, cwd=cwd)
    if exit_code != 0:
        exit(exit_code)

    if border in ('after', 'both'):
        print('=' * 80)


def fail(*args, **kwargs):
    print_message(*args, **kwargs, prefix='!!!', pad='both')
    exit(1)


def print_message(message: str, *components, pad: str= '', prefix: str = '   '):
    if pad in ('before', 'both'):
        print()

    print('  {}  {}'.format(prefix, message % (components)))

    if pad in ('after', 'both'):
        print()


def time_elapsed():
    return str(datetime.datetime.now() - START_TIME)


def write_manifest(bucket: str):
    runtimes = []
    for filename in sorted(glob.glob('*.tar.gz'), reverse=True):
        meta = PATTERN_FILENAME.match(filename).groupdict()

        with open(filename + '.shasum') as f:
            shasum = f.read().split()[0]

        runtimes.append({
            'id':     ID_TEMPLATE.format(**meta),
            'name':   NAME_TEMPLATE.format(**meta),
            'url':    URL_TEMPLATE.format(bucket=bucket, filename=filename),
            'shasum': shasum,
        })

    print_message('writing %s', MANIFEST_FILENAME)
    with open(MANIFEST_FILENAME, 'w') as f:
        f.write(MANIFEST_TEMPLATE.format(runtimes=json.dumps(runtimes, indent=4)))


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit(1)
